name: mssql
services: 
  server: 
    container_name: mssql 
    hostname: mssql 
    user: root
    environment: 
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer 
      - MSSQL_MEMORY_LIMIT_MB=8192
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup 
    ports: 
      - 1433:1433 
    volumes: 
      - mssql_data:/var/opt/mssql:rw 
    image: mcr.microsoft.com/mssql/server:latest 
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 8192M
        reservations:
          cpus: '0.1'
          memory: 50M
      restart_policy:
        condition: unless-stopped
        delay: 5s
        window: 120s

volumes:
  mssql_data:
    name: mssql_data
    external: false